### ISSUE TITLE
Format Citation

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/website#12]
The citations are currently formatted in listings using the apa.csl file, the mfish.bib file, and the pandoc-citeproc package. This works well. 

However, for some citations we want to add additional information #11, and have this change the format in the citation listings. In particular add links to the summary page, and any pdfs etc. Even add some html icons (css classes) etc. 

My feeling is that this should be done with some enhancement to the citeproc system, but open to suggestion. We want to continue to format the citations using the CSL statement, as it contains a lot of details.

See discussion in #9 and #10.

**Comment by spl** [comment]
See jgm/pandoc-citeproc#52 for issue of adding links to a citation in pandoc-citeproc. It's currently not supported.

**Comment by spl** [comment]
However, I do think this is possible with hacks. See my comments on #17.

Implementing it in pandoc-citeproc would be a useful contribution but would naturally take longer.

**Comment by finlay** [comment]
Hi Sean

We have been talking about this issue, and think we need more than can be achieved only in the pandoc-citeproc package.

There are a couple of aspects to this:

  1. Every time a citation is presented in a "references" section it needs to include information from a corresponding .md file. Ideally, all the YAML header content can be made available.
  2. The CSL mechanism should only be used for the actual citation text, which doesn't need to include links. The presence of the markdown file, and its information, should be combined with the citation text, and provided to a template that formats the actual citation.

So, we need a new template (/templates/publication/citation.html) that can be used to format the citations, and conditionally include the YAML data.

You are most of the way to implementing this functionality, so shouldn't be too hard to get it working.

F

**Comment by edwardabraham** [comment]
Hi @spl, did you make any progress on this? The idea is that *any* time a reference is formatted on the site it uses the `/templates/publication/citation.html` template, and so we get a consistent formatting (including links to the summary pages, pdf downloads, etc.) throughout the site.

**Comment by spl** [comment]
@edwardabraham Yes, it's part of #18, too. Sorry, I forgot to mention it in the summary. Currently, there are two templates, one for an entry in the list and one for the summary:

```html
<!-- content/templates/citation-entry.html -->
<h4>$title$</h4>
$citation$
$if(bibUrl)$ <a href="$bibUrl$">url</a> $endif$
$if(doi)$ $doi$ $endif$
$if(keywords)$ $keywords$ $endif$
```

```html
<!-- content/templates/citation-summary.html -->
<h2>Citation</h2>
$citation$
<h2>Summary</h2>
$if(bibUrl)$ <a href="$bibUrl$">url</a> $endif$
$if(doi)$ $doi$ $endif$
$if(keywords)$ $keywords$ $endif$
$body$
```

As you can see, the summary includes the `$body$` while the entry does not (among other differences). I'm not sure exactly how you want to format the citations on each page, but there may be a common part for both that can be factored out.

The issues are rather interdependent, so I've been working on them at the same time. All of them need the proper use of metadata fields and context in templates, and getting that right has been most of the work. Also, you say #14 is not a priority, but you do need the main publication list, which is a query-based citation list. I haven't worked on tags, and, if I understand you correctly, I think that's what you don't need right now.

**Comment by spl** [comment]
> The idea is that _any_ time a reference is formatted on the site it uses the `/templates/publication/citation.html` template, and so we get a consistent formatting (including links to the summary pages, pdf downloads, etc.) throughout the site.

Okay, I didn't understand the entire issue here initially.

The citations in the publication list use the citation template (mentioned above) because I'm generating that HTML myself by passing it through pandoc-citeproc. But the citations that are mentioned in the text or YAML header of a given `.md` file (such as news or posts) do not use the citation template. These are created by pandoc-citeproc directly and pandoc-citeproc does not provide access into the middle of this process. To do this, I think it will require manually finding the citations and producing the reference list using the template.

I'll look into this today.

**Comment by edwardabraham** [comment]
Idrally, I think you would override the call to citeproc, pass through the
citation, get that formatted, then add the other information using the
template.

Not sure of the mechanics of this, of course, but maybe @finlay can advise.
If you look at our existing website, you can see that the current
references have the citeproc generated bit, embedded in other information
from a template.

**Comment by spl** [comment]
> I think you would override the call to citeproc, pass through the citation, get that formatted, then add the other information using the template.

Right. That's what I'm doing now with the publication lists. But, in that case, I have a list of refs that I want to render. In the case where you have `@blah` somewhere in a `.md`, pandoc-citeproc is doing (at least) two things:

1. Replace `@blah` with a citation in the output
2. Render the bibliography and append it to the end of the output

The above steps are in [`Text.CSL.Pandoc. processCites`](https://hackage.haskell.org/package/pandoc-citeproc-0.7.2/docs/Text-CSL-Pandoc.html#v:processCites) with no way to intercept the process in the middle.

I can currently think of a couple of options for how to do it:

1. Deal with the HTML tag soup and insert extra HTML into the bibliography. This is ugly and likely to cause problems when things such as the CSL or Pandoc change. I'd rather not do this.
2. Use two different-but-nearly-identical `.csl` files:

    1. One without a `<bibliography>` section for only replacing `@blah` with a citation in the output
    2. Another with a `<bibliography>` section for rendering the references in the bibliography

    This option would probably involve a search for all of the `@blah` citations so that we know what references need to be rendered.
3. Do the above with the current `apa.csl` but do our own version of replacing `@blah` instead of using pandoc-citeproc.

**Comment by edwardabraham** [comment]
Aah. I had hoped you would be able to break into pandoc cite-proc in some way. I  can see 1) would be suspect, 2) seems hackish, and 3) looks like a lot of work. I am out of my technical depth here, so will have to defer to you and @finlay. Thanks, Sean.

**Comment by edwardabraham** [comment]
I think that we have enough flexibility now to do what we need to do, and so I am closing this issue.
