### ISSUE TITLE
Query based citation lists 

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/website#14]
The idea is to add a syntax to the scholarly markdown, supported in the pandoc-citeproc project, that will allow lists of citations to be prepared on the a basis of some kind of query. For example, this might be a publication date range, an author, or a tag/keyword.

**Comment by spl** [comment]
See jgm/pandoc-citeproc#142.

**Comment by finlay** [comment]
I guess the idea of having a custom bibtex file is equivalent to just listing the citations in the publications.md file.

**Comment by spl** [comment]
I would first go for filtering and sorting `[Reference]` as started in #17. Later, we can talk about the syntax needed to support these operations in Pandoc's Markdown, as we'll have a better idea of the semantics.

**Comment by edwardabraham** [comment]
Finlay and I talked today about adding a tag field to the summary .md YAML.
The tags could then be used for filtering and sorting. In this way, there
is no overloading or extending of the bibtex.

**Comment by spl** [comment]
> Finlay and I talked today about adding a tag field to the summary .md YAML. The tags could then be used for filtering and sorting. In this way, there is no overloading or extending of the bibtex.

Yes, that's what I was thinking about for keywords, which I'm guessing are the same idea as your tags.

I noted that you have a lot of references in `mfish.bib` that are not Dragonfly publications, and I'm guessing you want to only show Dragonfly citations on your overall list. So I'm thinking that you add a keyword to indicate this, and we filter on it.

For example, here's a summary `.md` file:

```markdown
---
keywords: [dragonfly]
---
Abstract ....
```

Since this has `dragonfly` in its keyword list, we include it in the list. If it doesn't, we drop it.

We then use the same approach to publish keyword-based lists for particular projects.

Does this fit your idea?

As I [mentioned](https://github.com/dragonfly-science/website/pull/17#issuecomment-119970301) in #17, getting metadata from the `.md` is not currently implemented, but it should be doable, if only hackish.

**Comment by edwardabraham** [comment]
Yep. Just like that. Nice and flexible, with all the config for a reference
in one place. In our current implementation, we put dragonfly author names
in as keywords, so they can be selected.

In the future, the same mechanism could be used  to give consistent tagging
across all the website content.

**Comment by edwardabraham** [comment]
Have been having discussions with @finlay, and we are going to use a tag mechanism
```
---
tags: apples, peaches, plums
---
```
This will be used to put classes on the bibliography items,  and the filters will then be made using javascript. This is nearly complete. This javascript based query based list will be good enough for now, and will be implemented for all the Collections (so the tag-based filtering will also be available for news, etc.).
